# https://taskfile.dev

version: '3'

includes:
  ansible: 
    dir: ./ansible
    taskfile: ./ansible/Taskfile.yaml
  virt-lightning:
    dir: ./virt-lightning
    taskfile: ./virt-lightning/Taskfile.yaml

tasks:
  default:
    cmds:
      - /usr/bin/go-task -l
    silent: true
  
  redo:
    desc: "Tear down and rebuild all lab"
    cmds:
    - task: virt-lightning:destroy
    - task: virt-lightning:create
    - task: ansible:playbook-init

  cluster-info:
    desc: Test access to the API Server
    env:
      KUBECONFIG:
        sh: echo $PWD/ansible/resources/.kube/config
    cmds:
    - kubectl cluster-info