# https://taskfile.dev

version: '3'

vars:
  VIRT_LIGHTNING_FILE: virt-lightning.yaml

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  destroy:
    desc: Destroy the whole bunch of machines
    cmds:
      - vl down {{ .CLI_ARGS }}
  
  create:
    desc: Create the lab machines
    cmds:
    - vl up {{ .CLI_ARGS }}

  start:
    desc: Start all VMs
    cmds:
    - |
      for vm in $(awk '/name/ { print $3 }' {{ .VIRT_LIGHTNING_FILE }}); do
        sudo virsh start ${vm}
      done