# https://taskfile.dev

version: '3'

vars:
  VIRT_LIGHTNING_FILE: virt-lightning.yaml

tasks:
  default:
    cmds:
      - task -l
    silent: true
  
  destroy:
    desc: Destroy the whole bunch of machines
    cmds:
      - vl down {{ .CLI_ARGS }}
  
  create:
    desc: Create the lab machines
    cmds:
    - vl up {{ .CLI_ARGS }}
