---
- name: Set prerequisites
  hosts: all
  become: true

  tasks:
  - name: Add containerd repo
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  - name: Add Kube Repo
    ansible.builtin.yum_repository:
      name: kubernetes
      description: Kubernetes Repo
      file: kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: 
      - kubelet 
      - kubeadm 
      - kubectl
      enabled: true
  - name: Install containerd
    ansible.builtin.yum:
      name: containerd.io
      state: latest
  - name: Enable containerd
    ansible.builtin.systemd:
      name: containerd
      state: started
      enabled: yes
  - name: Check nerdctl
    ansible.builtin.stat:
      dest: /usr/local/bin/nerdctl
    ignore_errors: true
    register: stat_nerdctl

  - name: Install nerdctl
    block:
      - name: Download nerdctl
        get_url:
          url: https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-1.1.0-linux-amd64.tar.gz
          dest: /tmp/
        register: bin_files
      - name: Unpack nerdctl
        ansible.builtin.unarchive:
          src: "{{ bin_files.dest }}"
          dest: /usr/local/bin
          copy: no
    when: not stat_nerdctl.stat.exists

  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled
    notify: System Restart
  - name: Install kube binaries
    ansible.builtin.yum:
      name: "{{ item }}"
      disable_excludes: kubernetes
      state: present
    with_items:
    - kubelet
    - kubeadm
    - kubectl
  - name: Enable kubelet
    ansible.builtin.systemd:
      name: kubelet
      state: started
      enabled: yes
  - name: Persist kernel modules
    ansible.builtin.lineinfile:
      dest: /etc/modules-load.d/k8s.conf
      create: true
      line: "{{ item }}"
    with_items:
    - overlay
    - br_netfilter
  - name: Enable kernel modules
    community.general.modprobe:
      name: "{{ item }}"
      state: present
    with_items:
    - overlay
    - br_netfilter
  - name: Enable sysctl stuff
    ansible.posix.sysctl:
      name: "{{ item }} "
      value: '1'
      state: present
      reload: yes
    with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
    notify: System Restart
  - name: Fix containerd
    ansible.builtin.lineinfile:
      dest: /etc/containerd/config.toml 
      line: disabled_plugins = [""]
      regexp: '^disabled_plugins.*$'
      state: present
    notify: Restart containerd


  handlers:
    - name: Restart containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
    - name: System Restart
      ansible.builtin.reboot:
